"""rename user column to role

Revision ID: 930cd9108f95
Revises: a6af019b3ebf
Create Date: 2026-06-25 21:44:45.672961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930cd9108f95'
down_revision: Union[str, Sequence[str], None] = 'a6af019b3ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('users', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
