"""initial migration

Revision ID: a6af019b3ebf
Revises: 
Create Date: 2026-06-25 21:03:47.263263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6af019b3ebf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_product', sa.String(), nullable=False),
    sa.Column('price_product', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('category_product', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('carts',
    sa.Column('id_cart', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_cart')
    )
    op.create_table('orders',
    sa.Column('id_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('cart_items',
    sa.Column('id_cart_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cart'], ['carts.id_cart'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_cart_item')
    )
    op.create_table('order_items',
    sa.Column('id_order_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_order_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('orders')
    op.drop_table('carts')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
